name: gg_hash
description: A simple FNV-1 hash implementation used across multiple projects within our organization.
version: 1.0.0
repository: https://github.com/inlavigo/gg_hash

environment:
  sdk: ^3.2.0

dev_dependencies:
  args: ^2.4.2
  coverage: ^1.7.2
  lints: ^3.0.0
  pana: ^0.21.45
  test: ^1.24.0
  yaml: ^3.1.2
