name: gg_hash
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-80.0.dev

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  args: ^2.4.2
  coverage: ^1.7.2
  lints: ^3.0.0
  pana: ^0.21.45
  test: ^1.24.0
  yaml: ^3.1.2
